#!/usr/bin/env python

import sys
import pymongo


def getServerStatus():
    host = "127.0.0.1"
    port = 27017
    c = pymongo.MongoClient(host, port)
    return c.admin.command('serverStatus', workingSet=True)

name = "locked"


def doData():
    for k, v in getServerStatus()["opcounters"].items():
        print("%s.value %s" % (k, v))


def doConfig():

    print("graph_title MongoDB operations")
    print ("graph_args --base 1000 -l 0 --vertical-label Ops")
    print ("graph_category MongoDB")

    for k in getServerStatus()["opcounters"]:
        print("%s.label %s" % (k, k))
        print k + ".draw LINE1"


if __name__ == "__main__":

    from os import environ
    if 'HOST' in environ:
        host = environ['HOST']
    if 'PORT' in environ:
        port = environ['PORT']
    if 'USER' in environ:
        user = environ['USER']
    if 'PASSWORD' in environ:
        password = environ['PASSWORD']

if len(sys.argv) > 1 and sys.argv[1] == "config":
    doConfig()
else:
    doData()
